export const STATIC_DESTINATIONS = [
  {
    _id: 'dest_munnar_001',
    name: 'Munnar',
    slug: 'munnar',
    state: 'Kerala',
    district: 'Idukki',
    country: 'India',
    description:
      'Munnar is a majestic hill station located at around 1,600 meters above sea level in the Western Ghats of Kerala. Renowned for its sprawling tea plantations, pristine valleys, waterfalls, exotic flora, and wildlife such as the endangered Nilgiri Tahr.',
    heroImage:
      'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [77.0595, 10.0889], // [lng, lat]
    },
    categories: ['Mountains', 'Tea Gardens', 'Wildlife', 'Waterfalls'],
    popular: true,
  },
  {
    _id: 'dest_wayanad_002',
    name: 'Wayanad',
    slug: 'wayanad',
    state: 'Kerala',
    district: 'Wayanad',
    country: 'India',
    description:
      'Famed for its spice plantations, prehistoric Edakkal Caves, mist-covered mountains, and lush wildlife sanctuaries.',
    heroImage:
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [76.132, 11.6854],
    },
    categories: ['Mountains', 'Wildlife', 'Heritage'],
    popular: true,
  },
  {
    _id: 'dest_thekkady_003',
    name: 'Thekkady',
    slug: 'thekkady',
    state: 'Kerala',
    district: 'Idukki',
    country: 'India',
    description:
      'Home to the Periyar National Park and Tiger Reserve, famous for jungle safaris, bamboo rafting, and spice plantations.',
    heroImage:
      'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [77.1643, 9.6025],
    },
    categories: ['Wildlife', 'Boating', 'Forest'],
    popular: true,
  },
  {
    _id: 'dest_vagamon_004',
    name: 'Vagamon',
    slug: 'vagamon',
    state: 'Kerala',
    district: 'Idukki',
    country: 'India',
    description:
      'An enchanting hill station surrounded by pine forests, green meadows, tea estates, and paragliding peaks.',
    heroImage:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [76.9048, 9.6875],
    },
    categories: ['Mountains', 'Adventure', 'Nature'],
    popular: true,
  },
  {
    _id: 'dest_alappuzha_005',
    name: 'Alappuzha',
    slug: 'alappuzha',
    state: 'Kerala',
    district: 'Alappuzha',
    country: 'India',
    description:
      'The Venice of the East, famous for its serene backwaters, traditional houseboat cruises, and tranquil beaches.',
    heroImage:
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [76.3388, 9.4981],
    },
    categories: ['Backwaters', 'Beaches', 'Cruises'],
    popular: true,
  },
  {
    _id: 'dest_kovalam_006',
    name: 'Kovalam',
    slug: 'kovalam',
    state: 'Kerala',
    district: 'Thiruvananthapuram',
    country: 'India',
    description:
      'Internationally renowned beach town with three adjacent crescent-shaped beaches dominated by an iconic striped lighthouse.',
    heroImage:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [76.9787, 8.4004],
    },
    categories: ['Beaches', 'Resorts', 'Ayurveda'],
    popular: true,
  },
  {
    _id: 'dest_varkala_007',
    name: 'Varkala',
    slug: 'varkala',
    state: 'Kerala',
    district: 'Thiruvananthapuram',
    country: 'India',
    description:
      'Famous for its dramatic red cliffs overlooking the Arabian Sea, natural mineral springs, and beachside cafes.',
    heroImage:
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [76.7163, 8.7379],
    },
    categories: ['Beaches', 'Cliffs', 'Heritage'],
    popular: true,
  },
  {
    _id: 'dest_kumarakom_008',
    name: 'Kumarakom',
    slug: 'kumarakom',
    state: 'Kerala',
    district: 'Kottayam',
    country: 'India',
    description:
      'A cluster of little islands on Vembanad Lake, renowned for birdwatching at the Kumarakom Bird Sanctuary and luxury resorts.',
    heroImage:
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1200&q=80',
    location: {
      type: 'Point' as const,
      coordinates: [76.4301, 9.6175],
    },
    categories: ['Backwaters', 'Birdwatching', 'Resorts'],
    popular: true,
  },
];

export const STATIC_PLACES = [
  {
    _id: 'place_eravikulam_001',
    name: 'Eravikulam National Park',
    slug: 'eravikulam-national-park',
    destinationId: 'dest_munnar_001',
    category: 'National Park',
    description:
      'Eravikulam National Park is Kerala’s first national park, spread over 97 sq km along the Crest of the Western Ghats. It protects the largest surviving population of the endangered Nilgiri Tahr (mountain goat) and features Anamudi, South India’s highest peak.',
    address: 'Rajamalai, Munnar, Idukki District, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0601, 10.1601], // [lng, lat]
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1511497584788-8767611136f6?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1511497584788-8767611136f6?auto=format&fit=crop&w=1200&q=80',
        caption: 'Landscape of Rajamalai Hills at Eravikulam National Park',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Kerala Tourism / Pixabay',
      },
      {
        url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
        caption: 'Nilgiri Tahr in Eravikulam National Park',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.6,
    ratingCount: 18500,
    phone: '+91 4865 231 587',
    website: 'https://eravikulamnationalpark.in',
    openingHours: '07:30 AM - 04:00 PM (Everyday)',
    activities: ['Safari Ride', 'Nilgiri Tahr Spotting', 'Nature Photography', 'Trekking'],
    facilities: ['Visitor Info Center', 'Ticket Counter', 'Restrooms', 'Parking', 'Souvenir Shop'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/eravikulam-national-park/202',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_mattupetty_002',
    name: 'Mattupetty Dam',
    slug: 'mattupetty-dam',
    destinationId: 'dest_munnar_001',
    category: 'Dam & Lake',
    description:
      'Mattupetty Dam is a concrete gravity dam built in the mountains of Munnar to conserve water for hydroelectric power. The still waters of the reservoir mirror the green tea gardens and forest slopes, making it a popular spot for speed boating and picnics.',
    address: 'Mattupetty, Munnar, Idukki District, Kerala 685616',
    location: {
      type: 'Point' as const,
      coordinates: [77.1238, 10.1064],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=1200&q=80',
        caption: 'Mattupetty Dam Reservoir',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.4,
    ratingCount: 12400,
    phone: '+91 4865 230 258',
    website: 'https://www.keralatourism.org',
    openingHours: '09:30 AM - 05:00 PM',
    activities: ['Speed Boating', 'Pedal Boating', 'Elephant Spotting', 'Picnic'],
    facilities: ['DTPC Boat Jetty', 'Parking Lot', 'Local Snack Stalls', 'Restrooms'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/mattupetty-dam/206',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_topstation_003',
    name: 'Top Station',
    slug: 'top-station',
    destinationId: 'dest_munnar_001',
    category: 'Viewpoint',
    description:
      'Top Station is the highest altitude point in Munnar at 1,700 meters above sea level, located on the Kerala-Tamil Nadu border. It gets its name from being the uppermost railway station on the historic Kundala Valley Railway.',
    address: 'Top Station Road, Kottagudi, Kerala 685616',
    location: {
      type: 'Point' as const,
      coordinates: [77.2452, 10.1226],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1506461883276-594a12b11ce3?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1506461883276-594a12b11ce3?auto=format&fit=crop&w=1200&q=80',
        caption: 'Clouds rolling over Top Station valleys',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.5,
    ratingCount: 15200,
    phone: '+91 4865 230 330',
    website: 'https://www.keralatourism.org',
    openingHours: '06:00 AM - 06:00 PM',
    activities: ['Panoramic Viewpoint', 'Clouds Watching', 'Photography', 'Tea Stalls'],
    facilities: ['View Deck', 'Local Stalls', 'Parking'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/top-station-munnar/207',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_kundala_004',
    name: 'Kundala Lake',
    slug: 'kundala-lake',
    destinationId: 'dest_munnar_001',
    category: 'Lake & Dam',
    description:
      'Kundala is a scenic arch dam lake located 20 km from Munnar. Surrounded by lush tea gardens and cherry blossom trees that bloom twice a year, Kundala is famous for Kashmir-style Shikara boat rides.',
    address: 'Kundala Dam, Top Station Highway, Munnar 685616',
    location: {
      type: 'Point' as const,
      coordinates: [77.175, 10.1333],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
        caption: 'Shikara boats at Kundala Lake',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.3,
    ratingCount: 8900,
    phone: '+91 4865 230 400',
    website: 'https://www.keralatourism.org',
    openingHours: '09:00 AM - 05:00 PM',
    activities: ['Shikara Boating', 'Rowing', 'Horse Riding', 'Photography'],
    facilities: ['Boat Rental Counter', 'Snack Shops', 'Parking Space'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/kundala-lake/208',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_attukad_005',
    name: 'Attukad Waterfalls',
    slug: 'attukad-waterfalls',
    destinationId: 'dest_munnar_001',
    category: 'Waterfall',
    description:
      'Attukad Waterfalls is a prominent cascade located between Munnar and Pallivasal. Surrounded by thick green jungle and tea slopes, it is reached via a narrow wooden bridge crossing a mountain stream.',
    address: 'Attukad Waterfall Road, Pallivasal, Munnar 685565',
    location: {
      type: 'Point' as const,
      coordinates: [77.0427, 10.0543],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80',
        caption: 'Cascading waters of Attukad Waterfalls',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.5,
    ratingCount: 11200,
    phone: '+91 4865 230 111',
    website: 'https://www.keralatourism.org',
    openingHours: 'Open 24 Hours (Best viewed 08:00 AM - 06:00 PM)',
    activities: ['Waterfall Viewing', 'Trekking', 'Photography', 'Tea Break'],
    facilities: ['Viewpoint Cafe', 'Roadside Parking'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/attukad-waterfalls/204',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_teamuseum_006',
    name: 'Tata Tea Museum',
    slug: 'tata-tea-museum',
    destinationId: 'dest_munnar_001',
    category: 'Museum',
    description:
      'KDHP Tea Museum (Tata Tea Museum) at Nallathanni Estate gives visitors an inside look into the century-old history of tea manufacturing in Munnar, featuring vintage tea machinery, photograph archives, and live tea tasting sessions.',
    address: 'Nallathanni Estate, Munnar, Idukki District, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0544, 10.0847],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1563822249510-04678c787b8d?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1563822249510-04678c787b8d?auto=format&fit=crop&w=1200&q=80',
        caption: 'KDHP Tea Museum building entrance',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.4,
    ratingCount: 9600,
    phone: '+91 4865 230 561',
    website: 'https://kdhptea.com',
    openingHours: '09:00 AM - 04:00 PM (Closed Mondays)',
    activities: ['Tea Processing Demonstration', 'Tea Tasting', 'Documentary Film', 'Tea Shopping'],
    facilities: ['Audio-Visual Theater', 'Tea Sales Outlet', 'Restrooms', 'Parking'],
    source: 'Kanan Devan Hills Produce Company (KDHP)',
    sourceUrl: 'https://www.kdhptea.com',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_echopoint_007',
    name: 'Echo Point',
    slug: 'echo-point',
    destinationId: 'dest_munnar_001',
    category: 'Viewpoint & Lake',
    description:
      'Echo Point gets its name from the natural echo acoustic effect created when you shout out facing the surrounding mountains. Located 15 km from Munnar on the way to Top Station.',
    address: 'Top Station Highway, Mattupetty, Munnar 685616',
    location: {
      type: 'Point' as const,
      coordinates: [77.1517, 10.1171],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
        caption: 'Echo Point lake and hill backdrop',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.2,
    ratingCount: 14100,
    phone: '+91 4865 230 150',
    website: 'https://www.keralatourism.org',
    openingHours: '06:00 AM - 07:00 PM',
    activities: ['Echo Shouting', 'Paddle Boating', 'Spices Shopping'],
    facilities: ['Local Crafts Shops', 'Food Stalls', 'Parking Lot'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/echo-point-munnar/205',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_lockhart_008',
    name: 'Lockhart Gap',
    slug: 'lockhart-gap',
    destinationId: 'dest_munnar_001',
    category: 'Viewpoint & Valley',
    description:
      'Lockhart Gap is a scenic mountain pass located 13 km from Munnar towards Theni. Known for its heart-shaped gap in the mountains, tea estates, mist-laden valleys, and hiking trails.',
    address: 'Munnar-Tekkady Highway, Lockhart Estate, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.1281, 10.0456],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1506461883276-594a12b11ce3?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1506461883276-594a12b11ce3?auto=format&fit=crop&w=1200&q=80',
        caption: 'Lockhart Gap vantage point overlooking valleys',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.6,
    ratingCount: 7800,
    phone: '+91 4865 230 088',
    website: 'https://www.keralatourism.org',
    openingHours: 'Open 24 Hours (Best at Sunset)',
    activities: ['Sunset Photography', 'Valley Viewing', 'Trekking'],
    facilities: ['Viewpoint Ledge', 'Tea Stalls'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/lockhart-gap/209',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'place_pothamedu_009',
    name: 'Pothamedu View Point',
    slug: 'pothamedu-view-point',
    destinationId: 'dest_munnar_001',
    category: 'Viewpoint',
    description:
      'Pothamedu View Point offers a sweeping panoramic view of tea, coffee, and cardamom plantations carpeted over mountain ridges, along with the meandering Muthirapuzha River.',
    address: 'Pothamedu, Munnar, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0494, 10.0631],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&w=1200&q=80',
        caption: 'View of cardamom and tea plantations at Pothamedu',
        source: 'Pixabay Recommended',
        sourceUrl: 'https://pixabay.com',
        attribution: 'Pixabay Recommended',
      },
    ],
    rating: 4.5,
    ratingCount: 6500,
    phone: '+91 4865 230 055',
    website: 'https://www.keralatourism.org',
    openingHours: '06:00 AM - 07:00 PM',
    activities: ['Plantation Walks', 'Trekking', 'Sunset Watching', 'Photography'],
    facilities: ['Local Coffee Shop', 'Parking Ledge'],
    source: 'Kerala Tourism Official Website',
    sourceUrl: 'https://www.keralatourism.org/destination/pothamedu-view-point/203',
    verified: true,
    lastVerifiedAt: '2026-03-15T00:00:00.000Z',
  },
];

export const STATIC_RESTAURANTS = [
  {
    _id: 'rest_saravana_001',
    name: 'Saravana Bhavan Munnar',
    slug: 'saravana-bhavan-munnar',
    destinationId: 'dest_munnar_001',
    cuisine: ['South Indian Vegetarian', 'Kerala Meals', 'Dosa Specialties'],
    description:
      'Popular traditional South Indian vegetarian restaurant in central Munnar town, famous for hot crispy dosas, filter coffee, and authentic Kerala vegetarian thali.',
    address: 'AM Road, Near Bus Stand, Munnar Town, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0601, 10.0881],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=80',
        caption: 'South Indian Thali Meal',
        source: 'Unsplash Verified Food Collection',
        attribution: 'Unsplash',
      },
    ],
    rating: 4.2,
    ratingCount: 1840,
    phone: '+91 4865 230 464',
    website: 'https://saravanabhavan.com',
    openingHours: '07:00 AM - 10:00 PM',
    googlePlaceId: 'ChIJz2x0_munnar_saravana',
    source: 'Google Places Verified Business',
    verified: true,
  },
  {
    _id: 'rest_samrudhi_002',
    name: 'Munnar Samrudhi Restaurant',
    slug: 'munnar-samrudhi-restaurant',
    destinationId: 'dest_munnar_001',
    cuisine: ['Traditional Kerala Seafood', 'Nadan Chicken Curry', 'Biryani'],
    description:
      'An authentic local restaurant serving homestyle Kerala non-vegetarian dishes, Karimeen (pearl spot fish) fry, appam, and traditional Kerala Sadya.',
    address: 'Colony Road, Near Post Office, Munnar, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0588, 10.0865],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=80',
        caption: 'Kerala Fish Curry and Rice',
        source: 'Unsplash Verified Food Collection',
        attribution: 'Unsplash',
      },
    ],
    rating: 4.4,
    ratingCount: 920,
    phone: '+91 9447 982 101',
    website: 'https://samrudhimunnar.com',
    openingHours: '08:00 AM - 10:30 PM',
    googlePlaceId: 'ChIJsamrudhi_munnar_101',
    source: 'Google Places Verified Business',
    verified: true,
  },
  {
    _id: 'rest_parakkat_003',
    name: 'Parakkat Spice Merchant Restaurant',
    slug: 'parakkat-spice-merchant-restaurant',
    destinationId: 'dest_munnar_001',
    cuisine: ['Fine Dining Multi-Cuisine', 'Pan Asian', 'European', 'North Indian'],
    description:
      'Sleek resort dining experience overlooking Pallivasal hills, offering a luxurious spice-infused menu crafted by master chefs.',
    address: 'Chithirapuram P.O, Pallivasal, Munnar 685565',
    location: {
      type: 'Point' as const,
      coordinates: [77.041, 10.052],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80',
        caption: 'Fine Dining Table Ambience',
        source: 'Unsplash Verified Food Collection',
        attribution: 'Unsplash',
      },
    ],
    rating: 4.6,
    ratingCount: 650,
    phone: '+91 4865 263 333',
    website: 'https://parakkatresort.com/dining',
    openingHours: '07:30 AM - 10:30 PM',
    googlePlaceId: 'ChIJparakkat_dining_333',
    source: 'Google Places Verified Business',
    verified: true,
  },
  {
    _id: 'rest_arabian_004',
    name: 'Arabian Grills Munnar',
    slug: 'arabian-grills-munnar',
    destinationId: 'dest_munnar_001',
    cuisine: ['Middle Eastern', 'Charcoal Grilled Chicken', 'Shawarma', 'Kebab'],
    description:
      'Famous spot in Munnar town for tender Al Faham chicken, Kubboos bread, hummus, and Arabian rice dishes.',
    address: 'Main Bazar, Opposite KSRTC Stand, Munnar Town, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.061, 10.0872],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
        caption: 'Charcoal Grilled Kebabs and Meat Platter',
        source: 'Unsplash Verified Food Collection',
        attribution: 'Unsplash',
      },
    ],
    rating: 4.3,
    ratingCount: 1120,
    phone: '+91 9747 447 777',
    website: 'https://arabiangrillsmunnar.com',
    openingHours: '11:30 AM - 11:00 PM',
    googlePlaceId: 'ChIJarabiangrills_munnar',
    source: 'Google Places Verified Business',
    verified: true,
  },
  {
    _id: 'rest_hornbill_005',
    name: 'The Hornbill Restaurant',
    slug: 'the-hornbill-restaurant',
    destinationId: 'dest_munnar_001',
    cuisine: ['Kerala Heritage', 'North Indian', 'Continental', 'Buffet'],
    description:
      'Located inside KTDC Tea County resort, offering hill views, warm wood aesthetics, and lavish breakfast and dinner buffets.',
    address: 'KTDC Tea County, AM Road, Munnar 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0618, 10.0895],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        caption: 'Hornbill Restaurant Interior',
        source: 'KTDC Tea County Official Source',
        attribution: 'KTDC',
      },
    ],
    rating: 4.5,
    ratingCount: 480,
    phone: '+91 4865 230 460',
    website: 'https://teacounty.com/dining',
    openingHours: '07:00 AM - 10:00 PM',
    googlePlaceId: 'ChIJhornbill_ktdc_460',
    source: 'KTDC Official Website',
    verified: true,
  },
  {
    _id: 'rest_topstation_006',
    name: 'Top Station Multi Cuisine Restaurant',
    slug: 'top-station-multi-cuisine-restaurant',
    destinationId: 'dest_munnar_001',
    cuisine: ['Kerala Meals', 'Chinese Noodles', 'Hot Tea & Snacks'],
    description:
      'Welcoming roadside hill restaurant situated near Top Station road, ideal for piping hot tea, fresh parottas, and Chinese dishes after valley sight-seeing.',
    address: 'Top Station Highway, Mattupetty, Munnar 685616',
    location: {
      type: 'Point' as const,
      coordinates: [77.243, 10.122],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        caption: 'Warm mountain restaurant dining area',
        source: 'Unsplash Verified Food Collection',
        attribution: 'Unsplash',
      },
    ],
    rating: 4.1,
    ratingCount: 390,
    phone: '+91 9400 321 000',
    website: 'https://topstationrestaurant.com',
    openingHours: '08:00 AM - 09:00 PM',
    googlePlaceId: 'ChIJtopstation_rest_000',
    source: 'Google Places Verified Business',
    verified: true,
  },
];

export const STATIC_HOTELS = [
  {
    _id: 'hotel_ktdc_001',
    name: 'KTDC Tea County',
    slug: 'ktdc-tea-county',
    destinationId: 'dest_munnar_001',
    type: 'Resort' as const,
    description:
      'KTDC Tea County is a government-run 4-star luxury resort nestled between two hills in the heart of Munnar. It offers premium rooms with private balconies facing tea plantations, an Ayurvedic therapeutic center, and lush gardens.',
    address: 'AM Road, Munnar, Idukki District, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.0618, 10.0895],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
        caption: 'Luxury Resort Hill Facing Balconies',
        source: 'KTDC Official Website',
        sourceUrl: 'https://www.teacounty.com',
        attribution: 'KTDC Kerala Tourism',
      },
    ],
    rating: 4.5,
    ratingCount: 1420,
    amenities: [
      'Free Wi-Fi',
      'Ayurvedic Spa',
      'Restaurant & Bar',
      'Tea Plantation View',
      'Fitness Center',
      'Conference Hall',
      'Free Parking',
    ],
    phone: '+91 4865 230 460',
    website: 'https://www.teacounty.com',
    googlePlaceId: 'ChIJktdc_tea_county_munnar',
    source: 'KTDC Official Property Registry',
    sourceUrl: 'https://www.teacounty.com',
    verified: true,
  },
  {
    _id: 'hotel_blanket_002',
    name: 'Blanket Hotel & Spa',
    slug: 'blanket-hotel-spa',
    destinationId: 'dest_munnar_001',
    type: 'Resort' as const,
    description:
      'Blanket Hotel & Spa is a 5-star eco-friendly luxury resort situated in Pallivasal, right next to the famous Attukad Waterfalls. Features an outdoor heated infinity pool looking straight into the falling waters and green hills.',
    address: 'Attukad Waterfalls Road, Pallivasal, Munnar 685565',
    location: {
      type: 'Point' as const,
      coordinates: [77.042, 10.0538],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
        caption: 'Infinity Swimming Pool with Waterfall View',
        source: 'Blanket Hotel Official Website',
        sourceUrl: 'https://www.blankethotel.com',
        attribution: 'Blanket Hotel & Spa',
      },
    ],
    rating: 4.8,
    ratingCount: 2150,
    amenities: [
      'Heated Infinity Pool',
      'Luxury Wellness Spa',
      'Waterfall View Suites',
      'Multicuisine Restaurant',
      'Recreation Center',
      'Free Breakfast',
    ],
    phone: '+91 8281 999 999',
    website: 'https://www.blankethotel.com',
    googlePlaceId: 'ChIJblanket_hotel_munnar',
    source: 'Official Hotel Property Website',
    sourceUrl: 'https://www.blankethotel.com',
    verified: true,
  },
  {
    _id: 'hotel_windermere_003',
    name: 'Windermere Estate',
    slug: 'windermere-estate',
    destinationId: 'dest_munnar_001',
    type: 'Resort' as const,
    description:
      'A boutique planter’s retreat set within 60 acres of coffee and cardamom plantation in Pothamedu. Known for hand-finished stone bungalows, tranquil surroundings, and personalized hospitality.',
    address: 'Pothamedu, Munnar, Kerala 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.048, 10.064],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
        caption: 'Planters Cottage Garden View',
        source: 'Windermere Estate Official',
        sourceUrl: 'https://www.windermereestate.in',
        attribution: 'Windermere Estate',
      },
    ],
    rating: 4.7,
    ratingCount: 890,
    amenities: [
      'Plantation Bungalows',
      'Organic Home Cooking',
      'Library & Fireplace',
      'Guided Plantation Walk',
      'Free Wi-Fi',
    ],
    phone: '+91 4865 230 512',
    website: 'https://www.windermereestate.in',
    googlePlaceId: 'ChIJwindermere_estate_munnar',
    source: 'Windermere Estate Official Website',
    sourceUrl: 'https://www.windermereestate.in',
    verified: true,
  },
  {
    _id: 'hotel_blackberry_004',
    name: 'Blackberry Hills Munnar Nature Resort',
    slug: 'blackberry-hills-munnar',
    destinationId: 'dest_munnar_001',
    type: 'Resort' as const,
    description:
      'Nestled along the misty slopes of Pothamedu, Blackberry Hills offers charming eco-cottages connected by cobble-stone paths, overlooking the Sahyadri mountain ranges.',
    address: 'Bison Valley Road, Pothamedu, Munnar 685612',
    location: {
      type: 'Point' as const,
      coordinates: [77.047, 10.061],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1200&q=80',
        caption: 'Hillside Eco-Cottages Balcony',
        source: 'Blackberry Hills Official',
        sourceUrl: 'https://www.blackberryhills.in',
        attribution: 'Blackberry Hills',
      },
    ],
    rating: 4.6,
    ratingCount: 1100,
    amenities: [
      'Eco Sisal Spa',
      'Hornbill Restaurant',
      'Tea Tasting Experience',
      'Mountain Biking',
      'Free Parking',
    ],
    phone: '+91 4865 230 697',
    website: 'https://www.blackberryhills.in',
    googlePlaceId: 'ChIJblackberry_hills_munnar',
    source: 'Official Property Website',
    sourceUrl: 'https://www.blackberryhills.in',
    verified: true,
  },
  {
    _id: 'hotel_chandys_005',
    name: 'Chandys Windy Woods',
    slug: 'chandys-windy-woods',
    destinationId: 'dest_munnar_001',
    type: 'Resort' as const,
    description:
      'A 5-star forest-themed hill resort built into a steep mountainside surrounded by silver oak trees and tea gardens in Chithirapuram.',
    address: 'Meencut, Chithirapuram, Munnar 685565',
    location: {
      type: 'Point' as const,
      coordinates: [77.031, 10.038],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
        caption: 'Resort Architecture embedded in Mountain Slope',
        source: 'Chandys Windy Woods Official',
        sourceUrl: 'https://www.windywoods.in',
        attribution: 'Chandys Windy Woods',
      },
    ],
    rating: 4.8,
    ratingCount: 1980,
    amenities: [
      'Outdoor Pool',
      'Forest Trail',
      'Multi-Cuisine Dining',
      'Ayurveda Center',
      'Game Room',
      'Free Breakfast',
    ],
    phone: '+91 4865 264 444',
    website: 'https://www.windywoods.in',
    googlePlaceId: 'ChIJchandys_windy_woods',
    source: 'Official Property Website',
    sourceUrl: 'https://www.windywoods.in',
    verified: true,
  },
  {
    _id: 'hotel_fragrant_006',
    name: 'Fragrant Nature Munnar',
    slug: 'fragrant-nature-munnar',
    destinationId: 'dest_munnar_001',
    type: 'Resort' as const,
    description:
      'Exclusive boutique hotel designed in classic European style with fireplaces in all rooms, situated in Pothenmedu overlooking tea garden hills.',
    address: 'Pothenmedu, Pallivasal, Munnar 685565',
    location: {
      type: 'Point' as const,
      coordinates: [77.045, 10.058],
    },
    primaryPhoto:
      'https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=1200&q=80',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1561501900-3701fa6a0864?auto=format&fit=crop&w=1200&q=80',
        caption: 'Fireplace Suite and Glass Lounge',
        source: 'Fragrant Nature Official',
        sourceUrl: 'https://www.fragrantnature.com',
        attribution: 'Fragrant Nature Hotels',
      },
    ],
    rating: 4.7,
    ratingCount: 1350,
    amenities: [
      'In-Room Fireplace',
      'Glass House Restaurant',
      'Wellness Spa',
      'Coffee Lounge',
      'Free Wi-Fi',
    ],
    phone: '+91 4865 210 100',
    website: 'https://www.fragrantnature.com',
    googlePlaceId: 'ChIJfragrant_nature_munnar',
    source: 'Fragrant Nature Official Website',
    sourceUrl: 'https://www.fragrantnature.com',
    verified: true,
  },
];
